[package]
name = "banyan"
version = "0.1.0"
authors = ["Nathan Kent <nate@nkent.net>"]

edition = "2018"

[dependencies]
crossbeam-channel = "0.3.8"
nng = { version = "0.5.0-rc.2", default-features = false }
log = "0.4"
futures = "0.1.25"

[dev-dependencies]
env_logger = "0.5"

[patch.crates-io]
"nng-sys" = { git = "https://github.com/jeikabu/nng-rust.git", branch = "tracking" }
"nng" = { path = "../nng-rs" }
