[package]
name = "banyan"
version = "0.1.0"
authors = ["Nathan Kent <nate@nkent.net>"]

edition = "2018"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[features]
default= ["build-nng"]
build-nng = ["nng/build-nng"]
ffi = ["env_logger"]

[dependencies]
nng = { version = "0.4", default-features = false }
log = "0.4"
failure = "0.1.3"
futures = "0.1.25"
env_logger = { version = "0.5", optional = true}

[dev-dependencies]
env_logger = "0.5"
